name: Deploy
on:
  push:
    branches:
      - master
jobs:
  get-commit-hash:
    name: Get Commit Hash
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.hash.outputs.hash }}
    steps:
      - uses: actions/checkout@v4
      - name: Get commit hash
        id: hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  push-container:
    name: Push Container
    uses: rosvik/workflows/.github/workflows/push-container.yml@main
    needs: get-commit-hash
    with:
      image: rosvik/248.no
      registry_url: cubby.no
      registry_username: ${{ vars.REGISTRY_USER }}
      build_args: |
        COMMIT_HASH=${{ needs.get-commit-hash.outputs.hash }}
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
  cubbyman-reload:
    name: Cubbyman Reload
    needs: push-container
    uses: rosvik/workflows/.github/workflows/cubbyman-reload.yml@main
    with:
      base_url: https://cubby.no
    secrets:
      credentials: ${{ secrets.CUBBYMAN_CREDENTIALS }}
