name: Push Container To Registry
on:
  push:
    branches:
      - master
      - rosvik/svelte-rewrite

jobs:
  podman-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get commit hash
        id: hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.hash.outputs.hash }}

      # Setup for multi architecture build
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: 248.no
          tags: master ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          oci: true
          layers: true
          containerfiles: |
            Containerfile
          build-args: |
            COMMIT_HASH=${{ steps.hash.outputs.hash }}

      - name: Push To cubby.no
        id: push-to-cubby
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: cubby.no/rosvik
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-cubby.outputs.registry-paths }}"
