name: Push Container
on:
  push:
    branches:
      - master
jobs:
  get-commit-hash:
    name: Get Commit Hash
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.hash.outputs.hash }}
    steps:
      - uses: actions/checkout@v4
      - name: Get commit hash
        id: hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  push-container:
    name: Push Container
    uses: rosvik/workflows/.github/workflows/push-container.yml@main
    needs: get-commit-hash
    with:
      containerfile: Containerfile
      image: rosvik/248.no
      tag: ${{ github.ref_name }} # git tag or short branch name
      registry_url: cubby.no
      registry_username: ${{ vars.REGISTRY_USER }}
      build_args: |
        COMMIT_HASH=${{ needs.get-commit-hash.outputs.hash }}
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
  cubbyman-reload:
    name: Cubbyman Reload
    runs-on: ubuntu-latest
    needs: push-container
    steps:
      - name: Cubbyman reload
        run: |
          curl -X POST --user ${{ secrets.CUBBYMAN_CREDENTIALS }} https://cubby.no/cubbyman/v1/reload
